version: '3'
services:
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
    volumes:
      - appdata:/var/www
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - db
    

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
